### ISSUE TITLE
Update Chrome Store privacy information

### ISSUE THREAD

**Issue by aidan-gibson** [adam-p/markdown-here#865] opened 2024-09-17 02:02 UTC
The Chrome Store has added privacy information that must be filled out to justify permissions. Without it, there is a scary warning:

<img width="685" alt="image" src="https://github.com/user-attachments/assets/baeb324f-927d-4746-975f-57281acddc96">

(Has the Firefox store (AMO) added something similar? Worth checking.)

**Comment by adam-p** [comment] 2024-10-05 00:29
Duplicate of #722

**Comment by adam-p** [comment] 2024-10-05 10:16
After looking at this more, I see it's not strictly about Manifest V3, and so not a dup. Cleaning it up and re-opening it.

**Comment by adam-p** [comment] 2024-10-12 21:56
Privacy info has been added in the Chrome Store draft release. It'll be live after I do some release testing.

**Closed by adam-p** 2024-10-12 21:56 UTC
