### ISSUE TITLE
thunderbird multipart messages: use plain markdown in text/plain part

### ISSUE THREAD

**Issue by wookietreiber** [adam-p/markdown-here#304] opened 2015-09-18 11:27 UTC
Using the example:

```
_Hello_ `Markdown` **Here**!
```

I format using markdown here and send it to myself. I end up with the following for the text/plain part of a multipart message (looking at message source, default Ctrl+U key binding):

```
/Hello/ |Markdown| *Here*!

â€‹
```

This seems to be thunderbirds default re-formatting of the text/html part it automatically generates when sending multipart messages.

It would be really awesome, if using markdown here would simply use the hand-written markdown as the text/plain part when writing multipart messages.

**Comment by adam-p** [comment] 2015-09-18 14:06
Duplicate of #63.

**Closed by adam-p** 2015-09-18 14:06 UTC
Labels: duplicate

**Comment by wookietreiber** [comment] 2015-09-18 15:59
Sorry, for posting a duplicate issue. I actually looked at the issues and filtered by thunderbird label, this is why I didn't find it. Would you please label both of these issues as well as possibly the ones referencing #63 as thunderbird. This would help future searches.

**Comment by adam-p** [comment] 2015-09-18 19:22
Done.
