### ISSUE TITLE
new option: Markdown source for plaintext version

### ISSUE THREAD

**Issue by vv01f** [adam-p/markdown-here#430] opened 2017-05-23 13:22 UTC
we have nice formatting for everyone that wants to read HTML and we have plain text for those who do not want that. I would prefer to have the possibility to include the markdown source for the plaintext version instead of simplifying it even more.

* [ ] new option "omit simplifying markdown for plaintext version"
* [ ] conditional simplification when option is not set

the linebreaks and encoding necessary for plaintext email should be kept in place still.

**Comment by adam-p** [comment] 2017-06-13 11:28
Can you give an example of what you want would look like? Do you mean plaintext raw HTML?

**Comment by vv01f** [comment] 2017-06-13 17:25
> Do you mean plaintext raw HTML?

No. The generated Email is Multipart. Two (or more with PGP etc.) parts to be exact: Plain and HTML. I would like to have the exact text I typed (Markdown) in the Plain part instead of a generated simplified thing made from the HTML.

> Can you give an example of what you want would look like?

Example

What I typed:

```
	# Test

	some text including a [link]

	## Subtest

	**more** text with *stuff*

	<!--  links-->

	[link]: http://test.com/
```

What MD-here made from it:

```
--eRAetBs2VvwdHaXm0Xm9Rw20o8lVq4mNf
Content-Type: multipart/alternative;
 boundary="------------3E69768F254AE5057376F61B"

This is a multi-part message in MIME format.
--------------3E69768F254AE5057376F61B
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable


  Test

some text including a link <http://test.com/>


    Subtest

*more* text with /stuff/

=E2=80=8B

--------------3E69768F254AE5057376F61B
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html>
  <head>

    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3Dutf=
-8">
  </head>
  <body bgcolor=3D"#FFFFFF" text=3D"#000000">
    <div style=3D"" class=3D"markdown-here-wrapper"
      data-md-url=3D"Thunderbird">
      <h1 style=3D"margin: 1.3em 0px 1em; padding: 0px; font-weight:
        bold;font-size: 1.6em;" id=3D"test">Test</h1>
      <p style=3D"margin: 1.2em 0px ! important;">some text including a <=
a
          href=3D"http://test.com/">link</a></p>
      <h2 style=3D"margin: 1.3em 0px 1em; padding: 0px; font-weight:
        bold;font-size: 1.4em; border-bottom: 1px solid rgb(204, 204,
        204);" id=3D"subtest">Subtest</h2>
      <p style=3D"margin: 1.2em 0px ! important;"><strong>more</strong>
        text with <em>stuff</em><br>
        <!--  links--></p>
      <div
title=3D"MDH:PHA+IyBUZXN0PC9wPjxwPnNvbWUgdGV4dCBpbmNsdWRpbmcgYSBbbGlua108=
YnI+PC9wPjxwPiMjIFN1YnRlc3Q8L3A+PHA+Kiptb3JlKiogdGV4dCB3aXRoICpzdHVmZio8Y=
nI+PC9wPjxwPiZsdDsh
LS0mbmJzcDsgbGlua3MtLSZndDs8L3A+PHA+W2xpbmtdOiBodHRwOi8vdGVzdC5jb20vPGJyP=
jwv
        cD48YnI+PGJyPg=3D=3D"
style=3D"height:0;width:0;max-height:0;max-width:0;overflow:hidden;font-s=
ize:0em;padding:0;margin:0;">=E2=80=8B</div>
    </div>
  </body>
</html>

--------------3E69768F254AE5057376F61B--
```

The first part you can see is not what I typed any more.
My argument is: Markdown is easy to read plaintext already, no need to make some other weird simplified text from the HTML again; and btw potentially lost content here as well due to the then parsed HTML comment.

**Comment by adam-p** [comment] 2017-06-13 17:35
Duplicate of #63. It's not going to be possible for webmail, but possibly for Thunderbird.

**Closed by adam-p** 2017-06-13 17:35 UTC
