### ISSUE TITLE
Use of dollar sign in inline code producing odd results

### ISSUE THREAD

**Issue by rfulkerson** [adam-p/markdown-here#288] opened 2015-06-24 19:28 UTC
When using the following in Gmail or Blackboard, the conversion is wonky due to the first line:

Markdown:
````
* Need `'$'` in constructor

* Constructor and `display` don't have parameters

* No `return` for `menuChoice`

* Method `display` should not call `menuChoice()`

* Input in `menuChoice` should use `input.next().charAt(0)`
````

The output:

    Need `’ in constructor

    Constructor and display don’t have parameters

    No return for menuChoice

    Method display should not call menuChoice()

    Input in menuChoice should use input.next().charAt(0)

    ` in constructor

    Constructor and 0.07960530809955746 don’t have parameters

    No 0.967272506292158 for 0.849369396167897

    Method 0.9170844589050049 should not call 0.31504472305241105

    Input in 0.1455992251161714 should use 0.2595394013807545

It appears to be the `$` that's throwing it off in the first line.  If I remove the first line entirely or change it to something like `'c'` (replacing the `$` with a regular character), it works like a peach.

This is feedback for a Java course I'm teaching, and one of the things the students need to do is initialize a `char` variable to a dollar sign character, so I'm trying to give them feedback to that effect, but getting the weird results.

I've tried escaping the `$` character (though I didn't see anything about needing to do that anywhere) and that doesn't seem to work.  :)

If I've missed something obvious, sorry for the bandwidth.  I've been using Markdown and Markdown Here for years and this is the first really weird conversion issue I've stumbled across.

Thanks for the great work!

Any insights?

**Comment by adam-p** [comment] 2015-07-14 13:21
It turns out the problem is user input gets passed as the replacement argument to a [`String.replace()` call](https://github.com/adam-p/markdown-here/blob/f457cdba53ebab079a65f17007308269819ebeec/src/common/mdh-html-to-text.js#L355), but the replacement argument isn't just a plain string -- it has [some magic values](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter), including "$`". 

The workaround is: Where you have one of the magic dollar-sign values, use two dollar signs. So, "$$`", etc.

Fixed in rev 498d796. Will be in next release.

Thanks.

---

Somewhat funny: The same problem seems to affect the Mocha test runner. When the test I added fails it prints out:
```
AssertionError: expected '`' to equal '`expected '`' to equal '
```

**Closed** 2015-07-14 13:20 UTC
