### ISSUE TITLE
Option can't be used in Firefox .

### ISSUE THREAD

**Issue by happyconfident** [adam-p/markdown-here#385] opened 2016-09-22 07:45 UTC
When you installed a Markdown Here in Firefox , you clicked the option from the Markdown Here and you would find the Firefox didn't work.

**Comment by juaalta** [comment] 2016-09-22 09:18
The same happens to me.
If I access the configuration from the URL directly, I get misconfigured and modify these options are not updated.
I used the next url: `resource: //markdown_here_common/options.html`
Firefox 49.0
Markdown Here: 2.12.0

**Comment by juaalta** [comment] 2016-09-22 15:46
I disabled the multithreading and does work.
It stopped working when activated multithreading.

**Comment by haililihai** [comment] 2016-12-27 03:06
I got the same issue in Firefox 50.0.1 (Linux & Win).
In Linux, when the "preferences" button is clicked, noting happen. While in Windows 7, when the "options" button is clicked, the Firefox is totally stuck! Just kill-and-restart works.

**Comment by veevax** [comment] 2017-02-10 16:42
Same issue, here. I tried to disable multi-threading but it didn't do the trick.
Anyone had more luck?

**Comment by adam-p** [comment] 2017-05-13 21:10
Duplicate of #369 (which will be fixed soon).

**Closed by adam-p** 2017-05-13 21:10 UTC
