### ISSUE TITLE
Make cursor stay in the same place when switching back an forth between edit and preview mode

### ISSUE THREAD

**Issue by joelostblom** [adam-p/markdown-here#296] opened 2015-08-12 17:32 UTC
Hi,
Placing the mouse cursor in the middle of a text and then switching to preview and back to edit again, will cause the cursor to appear at the top of the text. This is just a minor annoyance (a little more in long documents), but it would be great if the cursor would stay in place after preview and switching back to edit mode again. I am using Markdown Here v2.11.8  on Ubuntu 15.04, Chromium 43.0.2357.130.

**Comment by adam-p** [comment] 2015-08-15 20:13
Duplicate of #73 (and related to #36).

**Closed by adam-p** 2015-08-15 20:13 UTC
