### ISSUE TITLE
Incompatible with Thunderbird v60.0

### ISSUE THREAD

**Issue by marespiaut** [adam-p/markdown-here#515] opened 2018-08-09 18:31 UTC
Hello,

As the title says, the extension is not compatible with the newest version of Thunderbird.

**Comment by dugite-code** [comment] 2018-08-10 02:48
Options -> Advanced -> Config Editor...

if you set `extensions.strictCompatibility` false you can install it.

The only bug I have personally found is the Add-on Options re-direct dialogue is invisible and I've submitted a Pull request to fix that #513

**Comment by StuntsPT** [comment] 2018-08-14 13:02
Using @dugite-code workaround makes the extension work, but all the syntax highlighters are gone in my case.
Can you confirm this?

Thanks

**Comment by StuntsPT** [comment] 2018-08-14 13:06
BTW, this seems to be a dupe of #495.

**Comment by dugite-code** [comment] 2018-08-16 05:54
@StuntsPT I never used syntax highlighting myself so never noticed it was broken. But yes looks like there is an issue with it.

**Comment by evazquez00** [comment] 2018-08-17 15:50
Thunderbird 60.0 (64-bit) on MacOSX

@dugite-code workaround applied

$ shasum -a 256 markdown_here-2.13.2-fx.xpi
70e312fd35d6f531ba064298d135c920975570134f4327e66fe5e1aad614537b  markdown_here-2.13.2-fx.xpi

Thunderbird reports "This add-on could not be installed because it appears to be corrupt."

**Comment by dugite-code** [comment] 2018-08-20 00:40
@evazquez00 see https://github.com/adam-p/markdown-here/issues/495#issuecomment-413433869

**Comment by evazquez00** [comment] 2018-08-20 14:57
@dugite-code Modified the .rdf file as suggested in $495, it now installs, but it is unusable.  No "icon" in the composer, no options, etc.

**Comment by dugite-code** [comment] 2018-08-20 22:40
Yeah there looks to be a number of issues that need work. I've gotten basic functionality on my system but my mods mught not be enough on another

**Comment by adam-p** [comment] 2018-08-25 18:53
Closing as duplicate of #495.

**Closed by adam-p** 2018-08-25 18:53 UTC
