### ISSUE TITLE
Options window hangs in TB 49 and FF 48

### ISSUE THREAD

**Issue by r2evans** [adam-p/markdown-here#378] opened 2016-09-08 05:41 UTC
Clicking on the "Options" button to configure MDH now hangs. The "More" click works fine, just not "Options". Once the options button is clicked, nothing on the Add-Ons tab will respond to user input. The tab closes but even when re-opened it is still in an unresponsive state. Once I've tried to access the options page, the application itself will not close via the "X" (top-right) button, I have to kill it via TaskMgr.

I've tried with all other extensions (other than Startup Master) disabled, no change.

It is also hanging with FF 48.0.2 (same symptoms), so it may either be something new with the FF/TB system, or something else.

Win10Pro, TB-49, FF-48.0.2, MDH-2.12.0

**Comment by r2evans** [comment] 2016-09-13 18:15
I don't *think* it is caused by an off-screen pop-up (that either cannot get the full windows "focus" or does not subscribe to the normal key shortcuts for control).

- Clicking anywhere on TB after trying to open MDH "Options" gives a bell, as if there is a modal popup that the main window needs me to resolve/close before doing anything else. From this one might infer that it is a popup of some sort.
- TB/FF extension popups like this don't show up as separate processes or windows, so task manager (along with <kbd>Alt</kbd>-<kbd>Tab</Kbd> or <kbd>Win</kbd>-<kbd>Tab</kbd>) does not show them nor help find them.

However,

- All other extension-popups I have allow <kbd>Alt</kbd>-<kbd>Space</kbd> <kbd>N</kbd> to show the window menu, then down-arrow (moves to "Move") or up-arrow (moves to "Close (Alt+F4)"). These keyboard shortcuts (including <kbd>Alt</kbd>-<kbd>F4</kbd>) do not restore TB to a usable state.

Does MDH create its option popup in a unique/non-standard way?

(BTW: I also tried uninstalling, redownloading, reinstalling, no change.)

**Comment by adam-p** [comment] 2017-05-13 21:10
Duplicate of #369 (which will be fixed soon).

**Closed by adam-p** 2017-05-13 21:10 UTC
Labels: duplicate
