### ISSUE TITLE
Stopped working in Gmail after 2015-05-21: v2.11.8 update

### ISSUE THREAD

**Issue by dheerajbhaskar** [adam-p/markdown-here#279] opened 2015-05-26 12:15 UTC
On Firefox 38.0.1 Win8.1 64-bit

I'm note really sure what details are needed so I'll describe the steps I took.

Steps:
- Go to gmail. 
- go to a conversation
- click reply
- type some reply in markdown
- click shortcut (defined in your addon settings) (I've been using the same shortcut before update)

What happens:
All text gets selected

What's expected to happen:
Convert the markdown with rendered HTML.

Let me know if more details are needed.

**Comment by robred** [comment] 2015-05-26 20:44
I noticed that the preview in the Markdown Here settings page also no longer renders the Markdown.
![markdown here preview](https://cloud.githubusercontent.com/assets/2084237/7822879/b1900f14-03b5-11e5-85ba-6d1db90d15a4.png)

**Comment by adam-p** [comment] 2015-05-27 01:17
Duplicate of #278, which will be the main issue for this. Fix coming soon...

**Closed by adam-p** 2015-05-27 01:17 UTC

**Comment by dheerajbhaskar** [comment] 2015-05-27 03:58
Is there a workaround for this until fixed?

Regards,
Dheeraj

**Comment by dheerajbhaskar** [comment] 2015-05-27 04:03
Nevermind, got it.
Read all the other issues. Will use the newer albeit unreviewed version
referenced in #278.

**Comment by adam-p** [comment] 2015-05-27 11:34
The new version has been approved by Mozilla.

**Comment by dheerajbhaskar** [comment] 2015-05-27 16:12
Thanks I've already installed it.

Thanks for the amazing work :)
