### ISSUE TITLE
Markdown Here is not installing on Thunderbird 68.7.0

### ISSUE THREAD

**Issue by morozdan2003** [adam-p/markdown-here#612] opened 2020-04-09 14:31 UTC
I have tried to install versions from [Mozilla Addons Store](https://addons.mozilla.org), from Releases tab on this GitHub repository. It seems like extension is incompatible with that version of Thunderbird.

**Comment by ReekyMarko** [comment] 2020-04-17 14:23
Duplicate of #577
TLDR; This addon is abandoned. Last commit in this repo is from 2018.

**Closed** 2020-04-22 13:43 UTC
