### ISSUE TITLE
Not rendering in receiver's email.

### ISSUE THREAD

**Issue by jjroper** [adam-p/markdown-here#244] opened 2015-02-05 17:12 UTC
I have been using Markdown here for a while, and I noticed (unfortunately, not often enough to find the pattern) that when some people reply to me, quoting the message I sent, my message was written but not rendered in Markdown. When I sent it, it was clearly formatted correctly, and since Markdown here sends a reminder (and even if not), I am certain I rendered, so that in MY email, the format was correct. I then sent a message again, asking the person if that is how the original email looked and they said yes, all weird format. I have sent messages from both, Chrome and Thunderbird and this has happened. Problem?

**Comment by tkelley65** [comment] 2015-03-05 20:00
It always warns me, whether it renders or not. I can't ever tell if it is working, even if I send a mail to myself to double check first.

**Comment by adam-p** [comment] 2015-03-07 21:17
In Gmail -- in your Sent folder or whatever -- does the email look rendered to you?

**Comment by tkelley65** [comment] 2015-03-08 02:19
Actually I think it's fixed, I set everything back to default and now when
I toggle it switches between rendered and not-rendered. It never rendered
in the compose window itself before, which made me think that was the
expected behavior. Thanks. Great program.

Tim Kelley

**Comment by adam-p** [comment] 2015-03-08 02:52
@tkelley65: That's great. If you had just installed the extension, then the problem was probably that you needed to reload the page or restart the browser.

@jjroper: I would still like an answer to the question about whether your "Sent" email looks rendered.

I have two theories: 

1. The person replying to you is using a mail client that only allows the display of the plaintext version of the email. (Every email you send has a plain version and a rich version.) So it's not that the recipient isn't getting the rendered email -- they're just refusing to look at it.

2. In the Gmail web interface (but not Tbird) you can get the effect you describe if you have Gmail's "Plain text mode" turned on. (Issue #50.)

**Comment by adam-p** [comment] 2015-05-03 12:48
I'm closing this issue. You can re-open if there's more info. (Doing some issue clean-up.)

**Closed by adam-p** 2015-05-03 12:48 UTC
