### ISSUE TITLE
Support Thunderbird 68

### ISSUE THREAD

**Issue by Qqwy** [adam-p/markdown-here#577] opened 2019-09-09 04:42 UTC
After updating to Thunderbird 68, the add-on has become disabled.

I would be very happy if it could be updated to work with this new version :slightly_smiling_face: .

**Comment by light-wizard** [comment] 2019-09-09 18:32
Hi there!
First of all, I'd like to thank @adam-p for his amazing work: I use markdown-here in Thunderbird on a daily basis, and it works great!
For this very reason, I was really sad to see it disabled in Thunderbird 68. Is there any plan and ETA to make it supported again?

Thanks

**Comment by yhager** [comment] 2019-09-10 16:55
I don't know much (read: nothing) about add-ons development, but I really need this one to work on tb 68. I hacked the sources a bit and managed to install it. I don't know if it's good enough or not, but might be a start for whomever wants to take it further:
```
diff --git a/src/manifest.json b/src/manifest.json
index f3c5af4..4d1fae5 100644
--- a/src/manifest.json
+++ b/src/manifest.json
@@ -12,7 +12,7 @@
     "128": "common/images/icon128.png",
     "512": "common/images/icon512.png"
   },
-  "permissions": ["contextMenus", "storage"],
+  "permissions": ["menus", "storage"],
   "background": {"page": "chrome/background.html"},
   "content_scripts": [
     {
@@ -46,7 +46,15 @@
 
   ,"applications": {
     "gecko": {
-      "id": "markdown-here-webext@adam.pritchard"
+      "id": "markdown-here-webext@adam.pritchard",
+      "strict_min_version": "68.0"
+    }
+  }
+  ,"legacy": {
+    "type": "xul",
+    "options": {
+      "page": "common/options.html",
+      "open_in_tab": true
     }
   }
 }
```

I roughly followed this guide: https://developer.thunderbird.net/add-ons/updates

**Comment by dngray** [comment] 2019-09-11 06:07
This seems to be a duplicate of https://github.com/adam-p/markdown-here/issues/536

**Comment by Qqwy** [comment] 2019-09-11 06:41
> This seems to be a duplicate of #536

Is it, though? That issue talks about Thunderbird version 64.

**Comment by sklages** [comment] 2019-09-11 08:52
This is probably a dead project by now .. a pity. 
Interestingly there is no alternative to this add-on on addons.thunderbird.net.

**Comment by dngray** [comment] 2019-09-12 05:59
> Is it, though? That issue talks about Thunderbird version 64.

Thunderbird 64 was the beta, which is now what Thunderbird 68 became. So anything after Thunderbird 60.x wasn't going to work with this, including Thunderbird 69 which is the next version.

> ADD-ON SUPPORT: Restartless add-ons contineu to work if their authors have made the necessary minor adjustments. Non-restartless add-ons using XUL overlays are only supported if add-on authors have adapted them, and Lighting/Calendar is the only one we know that has been adapted.

Does this addon actually use XUL in any way? we should check the source.

**Comment by Martii** [comment] 2019-09-22 06:24
@yhager *(and perhaps everyone else too)*:

Thanks for that kick-start [up there](https://github.com/adam-p/markdown-here/issues/577#issuecomment-530026885). :smile_cat: 

Spent a little bit of time crash learning WebExtensions *(still fresh)*. With your patch, adam-p/markdown-here#459, and along with the remainder of the build instructions enabled *(clever build system btw)*  `$ make build` builds an install-able version here.




i.e.

``` diff
diff --git a/src/manifest.json b/src/manifest.json
index f3c5af4..4d1fae5 100644
--- a/src/manifest.json
+++ b/src/manifest.json
@@ -12,7 +12,7 @@
     "128": "common/images/icon128.png",
     "512": "common/images/icon512.png"
   },
-  "permissions": ["contextMenus", "storage"],
+  "permissions": ["menus", "storage"],
   "background": {"page": "chrome/background.html"},
   "content_scripts": [
     {
@@ -46,7 +46,15 @@
 
   ,"applications": {
     "gecko": {
-      "id": "markdown-here-webext@adam.pritchard"
+      "id": "markdown-here-webext@adam.pritchard",
+      "strict_min_version": "68.0"
+    }
+  }
+  ,"legacy": {
+    "type": "xul",
+    "options": {
+      "page": "common/options.html",
+      "open_in_tab": true
     }
   }
 }
diff --git a/utils/build.js b/utils/build.js
index 9274aab..7a32bf1 100644
--- a/utils/build.js
+++ b/utils/build.js
@@ -9,7 +9,7 @@
 var fs = require('fs');
 var file = require('file');
 var archiver = require('archiver');
-var MetaScript = require('MetaScript');
+var MetaScript = require('metascript');
 
 
 var BASE_DIR = '..';
@@ -22,7 +22,7 @@ var THUNDERBIRD_EXTENSION = file.path.join(DIST_DIR, 'thunderbird.xpi');
 
 var CHROME_INPUT = [/^manifest\.json$/, /^common(\\|\/)/, /^chrome(\\|\/)/, /^_locales(\\|\/)/];
 var FIREFOX_INPUT = CHROME_INPUT;
-var THUNDERBIRD_INPUT = [/^chrome.manifest$/, /^install.rdf$/, /^common(\\|\/)/, /^firefox(\\|\/)/];
+var THUNDERBIRD_INPUT = [/^manifest\.json$/, /^chrome.manifest$/, /^install.rdf$/, /^common(\\|\/)/, /^firefox(\\|\/)/, /^_locales(\\|\/)/];
 
 var CHROME_PLATFORM = 'chrome';
 var FIREFOX_PLATFORM = 'firefox';
```

This is the bare minimum I think to get it at least working "out of the box". I never used the Options of this extension so I have no idea what was working versus what wasn't/isn't. I might spend a little more time on a diff patch that can be applied with `$ git apply < diff.diff.txt` if I have time to debug.

Refs:
* Tested in Linux under TB 68.1.0 (64-bit) Release update channel
* [diff.diff.txt](https://github.com/adam-p/markdown-here/files/3639426/diff.diff.txt) applied at 1df5aee09cae90e2991db4e9cfb8c1b65a3c1898

**Comment by Martii** [comment] 2019-09-22 06:33
P.S. Don't forget to do:

``` console
$ cd utils
$ npm install
$ cd ..
```
... before building since the routine currently utilizes [*node*](https://github.com/nodejs/node).

**Comment by Martii** [comment] 2019-09-22 09:28
Noticed a glitch with the manifest.json.

Needs:

``` diff
diff --git a/src/manifest.json b/src/manifest.json
index 4d1fae5..e496210 100644
--- a/src/manifest.json
+++ b/src/manifest.json
@@ -50,11 +50,5 @@
       "strict_min_version": "68.0"
     }
   }
-  ,"legacy": {
-    "type": "xul",
-    "options": {
-      "page": "common/options.html",
-      "open_in_tab": true
-    }
-  }
+  ,"legacy": true
 }
```

... which seems to correct it so there aren't two entries in the menu *(Tools -> Add-on Preferences)*... one being "dead". The remaining options dialog menu entry still opens and opens in a new tab here. The duplication is possibly from the install.rdf `<em:optionsURL>...` entry and maybe how the XUL component works in this Thunderbird. IDK atm.

**Comment by EBoisseauSierra** [comment] 2019-09-23 11:43
Kudos to @Martii for the patch.
I've cloned the repo and applied it, done the `npm install` bit… but then I'm a bit lost regarding how to build/enable the patched add-on in TB. 
➥ Could you please details a bit more the required steps?

**Comment by light-wizard** [comment] 2019-09-23 15:23
@Martii , thanks for the patch, it works like a charm (at least for the functionalities I use...)

> It may require a fork as it seems that @adam-p isn't responding, he didn't respond to the email I sent him either clarifying whether or not he was still maintaining this. Though I do see he is still active based on his github contributions so who knows what is going on.

I agree with @dngray , this is too good a project to die like this, it should be forked. Still, @adam-p should have a say in it. Let's hope he gets back in touch...

@EBoisseauSierra (and/or anyone who's interested), here's the procedure I followed to make it work:
1. Clone the repo with git or svn `$ git clone https://github.com/adam-p/markdown-here.git`
2. Apply the patch `$ git apply < path/to/diff/file/diff.diff.txt`
3. Install modules with *npm* and return to root folder
        
        > $ cd utils
        $ npm install
        $ cd ..

4. Build an install-able version `$ make build` 
5. Built extensions files will be saved in "dist" sub-folder
6. Open Thunderbird, go to the Add-ons Preferences page, click on the gear icon and choose "Install Add-on From File..."
7. Install .xpi built addon
9. Thunderbird will need to restart in order to enable the Add-on
10. Enjoy!

Cheers!

**Comment by StuntsPT** [comment] 2019-09-23 23:47
@light-wizard Thank you for the detailed instructions. I have this extension working again in thunderbird 68.0.
And of course, thank you to @Martii @yhager for the patch.
But indeed, a fork might be in order. I was involved in a [similar fork](https://github.com/gTile/gTile/issues/1) two years ago, and the project moved from a single author to community driven.
Of course, everything was done with full approval of the original author. Maybe `markdown-here` could benefit from a similar event? If only @adam-p could let us know his plans for this awesome project...

**Comment by Martii** [comment] 2019-09-24 01:57
Sure wish https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions had better explanations of the permissions. Chromium/Chromes references at https://developer.chrome.com/apps/declare_permissions seems to be filled in a bit more.

The reason why I say this... is the change of permissions doesn't seem to be even needed for TB, in legacy mode, but *does* need to be there for Chromium/Chrome. So the:

``` diff
-  "permissions": ["contextMenus", "storage"],
+  "permissions": ["menus", "storage"],
```

... probably breaks building the extension .zip for Chromium/Chrome because `menus` isn't symmetric between browsers *(yet?)*. Anywho... topic is Thunderbird so I'll stick to that for the time being.

**Comment by Martii** [comment] 2019-09-26 00:38
Composed a rather complex markdown message in TB 68.1.x and it failed to send with `diff.diff.txt` only. Had to revert to TB 60.x. Not sure latest TB is ready for this AO yet even slightly modified.

**Comment by gbstan** [comment] 2019-10-09 12:42
Could the .xpi be posted here please? I am not sure I can follow these instructions. If some users have already built a version compatible with TB 68 it would really be useful to be able to have the .xpi install file.

**Comment by StuntsPT** [comment] 2019-10-09 13:54
@gbstan  I have uploaded my build here. Comes with absolutely no warranty of any kind. You can use it if you decide that you trust me, a perfectly random stranger on the internet.

[markdown_here.tar.gz](https://github.com/adam-p/markdown-here/files/3707544/markdown_here.tar.gz)

See how I got you to hesitate? That's why no one had posted a build before. It is actually quite buggy, but if you **really** need to use it, it kind of sort of works.

I think the whole extension needs a lot of work to be usable on an everyday basis.

**Comment by gbstan** [comment] 2019-10-09 17:33
Thank you! It seems to work for my use cases! Great

**Comment by KoSukeWork** [comment] 2019-10-30 01:56
> @gbstan I have uploaded my build here. Comes with absolutely no warranty of any kind. You can use it if you decide that you trust me, a perfectly random stranger on the internet.
> 
> [markdown_here.tar.gz](https://github.com/adam-p/markdown-here/files/3707544/markdown_here.tar.gz)
> 
> See how I got you to hesitate? That's why no one had posted a build before. It is actually quite buggy, but if you **really** need to use it, it kind of sort of works.
> 
> I think the whole extension needs a lot of work to be usable on an everyday basis.

Thank you ! Your build is very convenient and I think you are credible

**Comment by dngray** [comment] 2019-10-30 05:32
I have moved on from this and found a [better solution](https://unix.stackexchange.com/questions/108485/send-email-written-in-markdown-using-mutt#comment701854_108809) using pandoc. I [haven't been happy with Thunderbird](https://github.com/dngray/thunderbird-user.js#large_blue_diamond-unmaintained) for some time. I very rarely send emails in markdown or HTML as it is [rarely needed](https://useplaintext.email/#why-plaintext). This [secret sauce](http://nosubstance.me/post/mutt-secret-sauce/) looks to be just the thing I need on the occasion I do need to.

**Comment by GaVenga** [comment] 2019-11-03 09:36
With Manjaro AND Ubuntu 18.04 I get this ERROR:
(Thunderbird 68.2 launched in Terminal (bash))
JavaScript error: resource://gre/modules/AsyncShutdown.jsm, line 551: uncaught exception: undefined

when closing Thunderbird

**Comment by cgustave** [comment] 2019-11-04 10:46
Thanks for the Th 68 tuto, happy to see markdown back.
Great add-on, hope it can be officially maintained again.

**Comment by dohliam** [comment] 2019-12-14 10:56
The build shared by @StuntsPT above doesn't seem to work at all on Thunderbird 68.2.2 unfortunately.

A workaround for the meantime is to run Markdown text through something like [Remarkable](
https://jonschlinkert.github.io/remarkable/demo/) and just copy-paste the result into Thunderbird. Obviously this is not as convenient as markdown-here, but at least it produces a more-or-less usable result.

**Comment by dngray** [comment] 2019-12-15 02:25
I have been using [Mutt Secret Sauce](http://nosubstance.me/post/mutt-secret-sauce/) now for a while. It makes [fairly nice emails](https://rawgit.com/oblitum/typographic-email/master/dist/kitchen_sink.html), and also sends a plain-text part using multipart/alternative. [The template](https://gist.github.com/oblitum/6eeffaebd9a4744e762e49e6eb19d189#file-email-html) can be fully customized to your needs.

It uses [Pandoc](https://en.wikipedia.org/wiki/Pandoc) which is likely to be maintained well into the future. You can actually use any markup language you like, not just Markdown, but AsciiDoc or whatever else you fancy.

One of the features I really like about it, is the rendering with MIMEmbellish occurs when you send the email, which means the markdown copy gets saved in your outbox. This really handy if you need to reply to it, and make corrections as you get to keep the email in markdown format.

**Comment by fulster** [comment] 2020-01-13 07:35
> @gbstan I have uploaded my build here. Comes with absolutely no warranty of any kind. You can use it if you decide that you trust me, a perfectly random stranger on the internet.
> 
> [markdown_here.tar.gz](https://github.com/adam-p/markdown-here/files/3707544/markdown_here.tar.gz)
> 
> See how I got you to hesitate? That's why no one had posted a build before. It is actually quite buggy, but if you **really** need to use it, it kind of sort of works.
> 
> I think the whole extension needs a lot of work to be usable on an everyday basis.

Thanks a lot ! For now, it's working like a charm !

**Comment by earboxer** [comment] 2020-01-15 14:12
Maybe somebody should open a WIP Pull request so we can all report issues/make fixes/suggestions toward it.

**Comment by neilmayhew** [comment] 2020-01-15 17:43
There's an _insane_ number of forks of this repo (7.6K)! However, most of them are way behind the upstream repo.

I've added my own [fork][1] and created a [release][2] using the patches from this issue.

[1]: https://github.com/neilmayhew/markdown-here
[2]: https://github.com/neilmayhew/markdown-here/releases/tag/v2.13.4-community

The binary build in the release is identical to the one [posted][3] by StuntsPT except that it has the additional [patch][4] from Martii added. You can verify this by unpacking both `.xpi` files and comparing the directories.

[3]: https://github.com/adam-p/markdown-here/issues/577#issuecomment-540011543
[4]: https://github.com/adam-p/markdown-here/issues/577#issuecomment-533864706

The preferences dialog still doesn't work properly, although checking the box for TeX math support did work for me. Unfortunately, I'm not knowledgeable and motivated enough to fix the preferences dialog myself, but I'd welcome PRs from anyone who wants to work in this area.

**Comment by neilmayhew** [comment] 2020-01-15 17:49
FWIW, I also created a PR (#592) but it seems unlikely @adam-p will be interested in merging it.

**Comment by neilmayhew** [comment] 2020-01-15 17:52
I don't know what it would take to get a new binary uploaded to the add-ons store. If anyone has thoughts about that, please let me know.

**Comment by dngray** [comment] 2020-01-16 07:18
> I don't know what it would take to get a new binary uploaded to the add-ons store. If anyone has thoughts about that, please let me know.

It most likely won't. It will also most likely [break again with Thunderbird 78](https://developer.thunderbird.net/add-ons/tb78) without further development.

Someone will need to make a hard fork, check out code, and make changes. Uploading an tarball here is not sufficient.

The code will have to go through the review process:

- https://extensionworkshop.com/documentation/manage/resources-for-publishers/
- https://extensionworkshop.com/documentation/publish/add-on-policies/
- https://extensionworkshop.com/documentation/publish/source-code-submission/

**Comment by dngray** [comment] 2020-01-16 07:27
> There's an _insane_ number of forks of this repo (7.6K)! However, most of them are way behind the upstream repo.

That does not mean there is active development. Many click the fork button instead of the star. You can get a more accurate view of what the forks actually have done https://github.com/adam-p/markdown-here/network

**Comment by neilmayhew** [comment] 2020-01-16 17:34
The network view wasn't showing yesterday. It said there were too many forks and it just listed them. However, presumably due to my creating a new fork with commits in it, the network view is showing again.

The great majority of recent commits in the network are bots, either fixing dependencies or optimizing images. There are also a lot that appear to be plain mistakes (people adding stuff to the wrong repo) and others making changes that are useful only to the committer. I didn't see anything useful that isn't already in a PR to the upstream repo.

**Comment by foxpluto** [comment] 2020-01-20 17:52
Hi to all,

just to let you know I am very interested in this plugin too! 

Regards,
Stefano

**Comment by DoctorSubtilis** [comment] 2020-01-30 09:58
> @gbstan I have uploaded my build here. Comes with absolutely no warranty of any kind. You can use it if you decide that you trust me, a perfectly random stranger on the internet.
> 
> [markdown_here.tar.gz](https://github.com/adam-p/markdown-here/files/3707544/markdown_here.tar.gz)
> 
> See how I got you to hesitate? That's why no one had posted a build before. It is actually quite buggy, but if you **really** need to use it, it kind of sort of works.
> 
> I think the whole extension needs a lot of work to be usable on an everyday basis.

Thank you very much. It works with e-mails.  
But (how) could it works with **tasks** as well? It would be wonderful...

**Comment by capac** [comment] 2020-02-27 15:08
Thanks a lot, worked for me too!

**Comment by bojanra** [comment] 2020-05-10 12:49
> @gbstan I have uploaded my build here. Comes with absolutely no warranty of any kind. You can use it if you decide that you trust me, a perfectly random stranger on the internet.
> 
> [markdown_here.tar.gz](https://github.com/adam-p/markdown-here/files/3707544/markdown_here.tar.gz)
> 
> See how I got you to hesitate? That's why no one had posted a build before. It is actually quite buggy, but if you **really** need to use it, it kind of sort of works.
> 
> I think the whole extension needs a lot of work to be usable on an everyday basis.

I went into same problems after upgrading to Thunderbird 68.7.0.
The build works like perfect. Thanks!

**Comment by Wheest** [comment] 2020-10-18 11:10
I was using a version I'd patched and built for a while, however my package manager finally updated to Thunderbird 78.3.1.  This means the add-on will no longer work.

It will be a moderate development job to get it updated, and I don't know enough JS, let alone add-on development to update it.

Anyone that's looking for a less-than-ideal solution could try what I'm doing for now:

Using pandoc, convert your email in markdown to HTML:

```
pandoc email.md -t html -o email.html
```

Then copy the raw HTML, and in your Thunderbird compose window select `Insert`->`HTML`.  This will render your HTML.  

As well as being more time consuming, pandoc also has different the behaviour. E.g. I use a lot of `&nbsp;` in some of my markdown emails, which pandoc converts to spaces, which Thunderbird ignores.

**Comment by ljakab** [comment] 2020-12-11 15:12
Has anyone started an effort to get the extension migrated to MailExtensions? I wonder if some interested folks could get organized in a chat room, see what has been done, avoid duplicating effort, and use everyone's strengths and limited free time to revive the project?

**Comment by Wheest** [comment] 2020-12-11 18:12
@ljakab see #644, where we are discussing possible ways forward.

**Comment by ljakab** [comment] 2020-12-11 22:25
> @ljakab see #644, where we are discussing possible ways forward.

Yeah, I saw that issue too, but I thought posting here might have a wider blast radius for finding people willing to do some technical work on it. It looks like there is no current ongoing effort that we know of.

**Comment by neilmayhew** [comment] 2020-12-31 17:17
See the important new development on #644. @Qqwy, I think this issue can be closed now.

**Comment by Qqwy** [comment] 2021-01-02 10:25
@neilmayhew Thank you for reaching out. 

I'll close this issue, and eagerly look forward to progress in #644. :slightly_smiling_face:

**Closed** 2021-01-02 10:24 UTC
