### ISSUE TITLE
Firefox freeze trying to open Markdown Here options

### ISSUE THREAD

**Issue by jjroper** [adam-p/markdown-here#415] opened 2017-03-15 12:38 UTC
I don't know when it started, but when I went to tweak MDH options in Firefox (the most recent version, with a just re-installed MDH), nothing happened. I then clicked on anything within Firefox and got a "ping" noise and Firefox was completely unresponsive. I had to force close to restart. Since the first time, I have tried on and off. No luck. Any suggestions?

**Comment by r2evans** [comment] 2017-04-06 16:02
I have the same problem. I've been able to work around it this way. (This is not for the faint-of-heart, unfortunately.)

1. Go to *Tools > Developer Tools > Developer Toolbox*. It will prompt you to allow remote debugging, press "OK". (I suspect it's using Firefox's remote debugging console.)

2. I grabbed the following code from [markdown-here source](https://github.com/adam-p/markdown-here/blob/dc1454ecb26a95120a8662461c9629911dbc0638/src/install.rdf#L159-L167). Copy and paste it into the entry field (bottom of the "Console" tab):

    ```js
                var windowMediator = Components.classes['@mozilla.org/appshell/window-mediator;1']
                                               .getService(Components.interfaces.nsIWindowMediator);
                var optionsUrl = 'resource://markdown_here_common/options.html';
                if (navigator.userAgent.indexOf('Thunderbird') >= 0 ||
                    navigator.userAgent.indexOf('Icedove') >= 0) {
                    windowMediator.getMostRecentWindow('mail:3pane')
                                  .document.getElementById('tabmail')
                                  .openTab('contentTab', {contentPage: optionsUrl});
                }
    ```

Don't mis-understand me: there is definitely a bug, and I've seen no activity from @adam-p in a while, but this allows me to at least access the MDH configuration.

(Win10-x64, TB 52.0b4 (32-bit), MDH 2.12.0)

**Comment by adam-p** [comment] 2017-05-13 21:12
Duplicate of #369 (which will be closed soon).

**Closed by adam-p** 2017-05-13 21:12 UTC
