### ISSUE TITLE
Problem with the Emphasis part in the Markdown Here Cheatsheet

### ISSUE THREAD

**Issue by aman5319** [adam-p/markdown-here#449] opened 2017-08-22 11:55 UTC
Your cheatsheet says for 
Combined emphasis with **BoldItalics and _BoldItalics_** ,
this doesn.t work instead after lots of hit and trail i got the answer that is for both Bold and Italic one should use in the manner
_**BoldItalics**_

**Comment by adam-p** [comment] 2017-10-26 21:22
I can't reproduce this. And your example in the issue above looks correct. And the cheatsheet render looks correct.

Both of these look right to me:
```
**_insideout_**
_**outsidein**_
```

They both work in Github:
**_insideout_**
_**outsidein**_

And they both work for me in Chrome+Gmail.

I'm closing this, but if you can provide more info we'll re-open and investigate.

**Closed by adam-p** 2017-10-26 21:22 UTC

**Comment by ViniciusBRodrigues** [comment] 2017-11-14 16:22
Bold simply doesn't work for me. I have tried many web browsers.
