### ISSUE TITLE
Firefox e10s multiprocessor compatibility

### ISSUE THREAD

**Issue by hyiltiz** [adam-p/markdown-here#419] opened 2017-04-05 19:49 UTC
Firefox only runs in multiprocessor mode when all of the addons are e10s compliant and uses multiprocessors threads. Markdown Here already has a WebExtention port for Chrome, so I assume implementing its e10s counterpart for Firefox should not be too much work (hopefully?), if not it is already done. 

Can you provide us what are your plans on this? Or you are planning to drop support for Firefox as quite a few famous/popular addons did?

**Comment by navinpai** [comment] 2017-06-14 07:19
Hey, 
You can update your extension to use the new Web API version.

https://github.com/adam-p/markdown-here/releases/tag/v2.13.1 (This is now also live on the Mozilla Addons).

Please close the issue once done so that the noise can be reduced! :)

**Comment by adam-p** [comment] 2017-06-14 14:08
Thanks for pointing out that there's another issue about e10s. 

So, duplicate of #207. Fixed with 2.13.1. Get the new Firefox WebExtensions version of MDH here:
https://addons.mozilla.org/en-US/firefox/addon/markdown-here/

**Closed by adam-p** 2017-06-14 14:08 UTC
